### ISSUE TITLE
Expired Apple Root CA Certificate used to sign in the two packages

### ISSUE THREAD

**Issue by parasnath-sumo** [autopkg/n8felton-recipes#106]
While installing brotherprinterdrivers4.1.1.dmg and ricohprinterdrivers3.0.dmg 
Munki is giving message that certificate used to sign these packages are expired..

See the attached screenshot
<img width="1440" alt="Screenshot 2019-11-04 at 3 14 18 PM" src="https://user-images.githubusercontent.com/43057901/68118650-85caa080-ff26-11e9-81e9-22c1375fad49.png">
<img width="1680" alt="Screenshot 2019-10-25 at 5 21 02 PM" src="https://user-images.githubusercontent.com/43057901/68118672-92e78f80-ff26-11e9-923c-3c2f8e205860.png">

**Comment by parasnath-sumo** [comment]
Strangely this is impacting only fresh mac computers, which we are configuring for the first time.(New laptops)

On existing Macs, with MSC already installed, these packages get installed without any issue

**Comment by n8felton** [comment]
This was likely due to The Apple Packagepocalypse, 2019 Edition (https://medium.com/@hammen/the-apple-packagepocalypse-2019-edition-6e2d4bc0aa90). Removing these affected drivers/packages from your Munki repo and running the AutoPkg recipes again should pull in updated packages from Apple with new/working certificates.
