### ISSUE TITLE
Microsoft Edge Product ID Change

### ISSUE THREAD

**Issue by walkintom** [autopkg/n8felton-recipes#146]
I've noticed the URLProvider is still pulling down Stable 89, when 90 was released last week. It appears the product ID (for at least stable) has changed from 2093438 to 2093504.

**Comment by n8felton** [comment]
A few things here.

Up front, @timnotton put in #143 and updated the LinkIDs to point to the universal installers, specifically 2093504 as you noted.

You will still need to update your override to point to the `Stable` channel instead of the default `Enterprise-Stable` channel.

As noted at https://docs.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule
> Starting with Stable channel version 94, Microsoft Edge is moving to a 4-week major release cycle cadence. However, we recognize that enterprise customers who manage complex environments need more time to plan and test Microsoft Edge updates. To help our enterprise customers who need an extended timeline to manage updates, Microsoft Edge will offer an Extended Stable option aligned to a longer, 8-week major release cycle; this option will only be available for customers with managed environments.

so I expect there will still need to separate `Stable` and `Enterprise-Stable` channels in the future, and that `Enterprise-Stable` will be slightly behind `Stable`.
