### ISSUE TITLE
HP Printer Drivers Download, product_number in Input?

### ISSUE THREAD

**Issue by foigus** [autopkg/n8felton-recipes#82]
The HP Printer Drivers [.download recipe](https://github.com/autopkg/n8felton-recipes/blob/master/HPPrinterDrivers/HPPrinterDrivers.download.recipe) would be more flexible if `product_number` was available as `Input` rather than hard-coded inside the recipe itself.

**Comment by cwhits** [comment]
My issue with making an `Input` variable is that once you `make-override` on the recipe, you'll never know if that `Input` variable gets updated upstream. Trust verification wont fail if that is ever updated in the upstream repo because it's an input variable.

I just had this issue with the Inkscape munki recipe where there are two `SEARCH_PATTERN`'s set as input variables. I started getting errors that the search pattern wasn't matching and no amount of `repo-update` would fix it because it was an input variable. It wasn't until I went to the github repo to start looking in to what needed to be changed that I realized the input variables were different between my override and the upstream recipe.

**Comment by ygini** [comment]
@cwhits the fact Inputs aren't in security checks should not lock us to make things usable… I came here exactly for the same things.

`product_number` must be a variable to make this useful for everyone…

**Comment by childrss** [comment]
From a support standpoint this is a very valid concern:  if you do repo-update and someone has done the work to fix the problem, it should be designed such that it fixes your problem as well.

The biggest waste in life is human time:  you never get it back.  Therefore if someone/something wastes your time, it is quite literally killing you.

M@

On Jan 24, 2018, at 3:43 PM, Chris Helming <notifications@github.com<mailto:notifications@github.com>> wrote:


My issue with making an Input variable is that once you make-override on the recipe, you'll never know if that Input variable gets updated upstream. Trust verification wont fail if that is ever updated in the upstream repo because it's an input variable.

I just had this issue with the Inkscape munki recipe where there are two SEARCH_PATTERN's set as input variables. I started getting errors that the search pattern wasn't matching and no amount of repo-update would fix it because it was an input variable. It wasn't until I went to the github repo to start looking in to what needed to be changed that I realized the input variables were different between my override and the upstream recipe.

**Comment by ygini** [comment]
So this should be a bug report on autopkg project. 

Limiting this recipe here will just lead to one result: I will make a duplicate to fit everyone else needs and it will generate confusion.

**Comment by cwhits** [comment]
@ygini do you have a product number you'd like to use? is it a matter of the recipe simply needing to be updated to a new product number or do you anticipate having multiple overrides to be able to use multiple `product_number`'s?

**Comment by MLBZ521** [comment]
I don't actually understand the issue here, unless I'm missing something?

The point of the override variables (in input) is to override it if you want to use a different value.  If you do not want to use a different value, then don't use the input override variable.  Not including it in your override will leave it as what's "default" in the parent recipe and all changes will thus be included in your downstream recipe.

i.e.  You only need input override variables for things you want to _change_.
